//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nHydrate2.DslPackage
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "nhydrate2";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"nHydrate2 Designer";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"jsrsoft.co.uk";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "99.99.0.1";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID nHydrate2DiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(nHydrate2CommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID nHydrate2ExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(nHydrate2CommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewnHydrate2ExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(nHydrate2CommandSetId), 0x0001);
	
		// Package identifier
		public const string nHydrate2PackageId = "36220dab-63c7-4daa-860c-fc548bf48888";
		
		// Editor factory identifier
		public const string nHydrate2EditorFactoryId = "29e4af38-a8e4-4323-a69b-b69b971f9999";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string nHydrate2ModelExplorerToolWindowId = "383b4f2d-0240-4258-beba-da8a6a0c3ab6";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace nHydrate2.DslPackage
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string nHydrate2CommandSetId = "539ee4bb-de7e-4658-94ea-87e1c8557777";
	}
}